### ISSUE TITLE
Add alt text to images in README.md

### ISSUE THREAD

**Issue by isabela-pf** [chanzuckerberg/sci-components#107]
Hi there! I'd like to add [alt text](https://en.wikipedia.org/wiki/Alt_attribute) to describe the content of the the two images on the [readme of this repo](https://github.com/chanzuckerberg/sci-components#readme). It's a tiny change that won't impact the actual components or change the way the readme renders.

I already have some [alt text written on my own fork](https://github.com/isabela-pf/sci-components/tree/alttext). I'd be happy to open a PR and contribute this, I just wanted to open an issue for discussion first. 

Let me know if you have any questions or things I should consider!

**Comment by tihuan** [comment]
Hi @isabela-pf ! Thank you so much for creating this issue and adding alt text to the images 🙏 ! My apologies for getting back to you this late 😭 

YES PLEASE! We'd love to have a PR and merge this 🎉 

Thanks again!

**Comment by isabela-pf** [comment]
No apology needed; the alt text isn't going to get impatient in my fork. 😆 Thanks for the vibrant enthusiasm!
