### ISSUE TITLE
Amend existing component: ComplexFilter

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/sci-components#112]
## Component to amend

ComplexFilter

## Exists or New

Exists. In use on https://napari-hub.org

## Visual

~Provide a screenshot or link to a prototype of your component changes.~ N/A

## Context

When performing a multiple selection, one of our users reported that they were confused by how to apply the filter (see 🧵 https://github.com/chanzuckerberg/napari-hub/discussions/299#discussioncomment-2083527)

We'd like to propose some changes to the ComplexFilter multi-select to make it more clear for users when their selection is applied.... specifically, for the filter to immediate apply when the box is checked, but leave the dialog open so users can continue to select additional filters.

We're tracking this at https://github.com/chanzuckerberg/napari-hub/issues/420

cc @liaprins-czi @codemonkey800

**Comment by codemonkey800** [comment]
Also, it would be nice to have a prop to disable / enable closing the filter on click so that we can maintain compatibility with other users of SDS in case they are used to and prefer the current functionality

**Comment by tihuan** [comment]
Hey all! Thanks so much for raising this and writing up an issue for tracking 🙏 

It feels like adding support for this should be pretty straight forward through a new boolean prop on `ComplexFilter`

@codemonkey800  what do you think the new prop’s name should be? I'm thinking something to the effect of `isTriggerChangeOnOptionClick` to convey that ComplexFilter's onChange will fire whenever an option is clicked. But not sure if it's too lengthy or something lol

And for clarification, disable/enable closing the filter on click will be another prop than the one above, right?

Thank you!

**Comment by tihuan** [comment]
@codemonkey800 gentle ping just in case 😄 Thank you!

**Comment by codemonkey800** [comment]
Sorry about that, thought I replied to this! 

I think it looks fine tbh haha If I had to suggest something, I've seen some libraries use string type for this. Maybe something like:"

```ts
interface Props {
  onChangeTrigger: 'on-close' | 'on-click';
}
```

> And for clarification, disable/enable closing the filter on click will be another prop than the one above, right?

I thought the closing of the filter was coupled with when the option `onChange` is triggered. If these can be done independently, I can see a separate prop being useful :)

**Comment by tihuan** [comment]
No worries! Thanks for your quick response 🤩 

Ahh `onChangeTrigger` with event types is a great idea! I think MUI did something similar for v4 Dialog's `disableBackdropClick` prop to decrease API surface 💡 

<img width="956" alt="Screen Shot 2022-02-02 at 10 27 02 AM" src="https://user-images.githubusercontent.com/6309723/152215226-0c79d51e-9275-4ed8-9d9f-d7c5fd9f169f.png">

In our case, it does feel like `isTriggerChangeOnOptionClick` might be enough lol Maybe we'll go with that for now and keep `onChangeTrigger` in mind if we need to support more trigger events down the road?

>> And for clarification, disable/enable closing the filter on click will be another prop than the one above, right?

>I thought the closing of the filter was coupled with when the option `onChange` is triggered. If these can be done independently, I can see a separate prop being useful :) 

Ah, I see what you mean now! Yeah I'm thinking it can be done independently in the sense that:

1. If `isTriggerChangeOnOptionClick` is `true`
2. In multi-select mode, when options dropdown is open
3. User selects one option, we will trigger onChange in the background AND still keep the dropdown open <-- Is this where you were thinking we'd close the dropdown right after click, thus having a second new prop to keep the menu open after click would be useful?

If so, I think we're on the same page and we don't need the second new prop, if step 3 can keep the dropdown open after click 🙆‍♂️ ?

**Comment by codemonkey800** [comment]
> Maybe we'll go with that for now and keep onChangeTrigger in mind if we need to support more trigger events down the road?

sounds good! let's keep it simple until we need the use case.

>  Is this where you were thinking we'd close the dropdown right after click, thus having a second new prop to keep the menu open after click would be useful?

oh no I was thinking more along the lines of having a prop to close the dropdown on click. one of the feedback we got was:

> https://github.com/chanzuckerberg/napari-hub/discussions/299#discussioncomment-2084528
> Oh! I see now! Click to select then click somewhere else.
Ok, that works, but man I can't say that behaves like any other such widget I've used before.
Especially since clicking on the sub-categories visually does something (they blink) but then doesn't invoke anything.
I'd prefer either the actual click on sub-category doing the action of filtering or the highlight being permanent and then adding a filter/apply button.

However, it seemed like the team was on the fence of keeping it open vs closing it after clicking one option. @liaprins-czi  @neuromusic what do you think? When clicking on a multi-select option, would you prefer keeping it open or closing the dropdown after clicking on an option?

**Comment by tihuan** [comment]
Oh! I thought the user was saying he was expecting the action of filtering happens every time an option is clicked (but the dropdown stays open), and not necessarily clicking an option will close the dropdown and then trigger filtering 😆 

I'm thinking in multiple select mode, closing the dropdown after each selection might take many clicks to select multiple values?

**Comment by neuromusic** [comment]
> I'm thinking in multiple select mode, closing the dropdown after each selection might take many clicks to select multiple values?

Agreed. Checkbox selection applies filter, but dropdown stays open to allow for multiple selection.

**Comment by tihuan** [comment]
Thanks for the quick responses, everyone 🚀 !

@codemonkey800 so it sounds like we can just add `isTriggerChangeOnOptionClick` prop to ComplexFilter to achieve the behavior we need now?

If so, I'll create a ticket in Shortcut and get it pulled into the next SDS sprint 🙆‍♂️ 

Thank you!

**Comment by tihuan** [comment]
Done! https://app.shortcut.com/sci-design-system/story/183624/add-istriggerchangeonoptionclick-to-complexfilter 

Thanks again, all! 🚀

**Comment by tihuan** [comment]
Hi all! This feature has been merged and released 17 days ago, so I'll close this now 🎉 Thank you!
