### ISSUE TITLE
Ongoing: update to MUI v5

### ISSUE THREAD

**Issue by mdjmoore** [chanzuckerberg/sci-components#120]
The following components would benefit from an upgrade to v5 of MUI - [shortcut ticket](https://app.shortcut.com/sci-design-system/story/185930/material-ui-mui-v5-todos):
- Button (v5 allows for intents)
- Tooltip (v5 has the `followCursor` prop by default, which tooltipTable and tooltipCondensed use)
- Tabs (TabsProps)

**Comment by masoudmanson** [comment]
These components have been modified in accordance with SDS's migration to MUI V5.
