### ISSUE TITLE
MenuSelect exposes unused props

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/sci-components#121]
`MenuSelect` accepts props in the shape of `MenuSelectProps<T, Multiple, DisableClearable, FreeSolo>`, but does not pass all props accordingly.

If I provide a `placeholder` prop, I would expect it to show, but it looks like input props aren't properly passed to the input.

You can see here on line 78 that `placeholder` is hard-coded and on line 98 props are spread to `Autocomplete`, but props aren't spread to the `Input`.

https://github.com/chanzuckerberg/sci-components/blob/062e0f5abeb52db96ac0d8598ff364f33bb4e865/src/core/MenuSelect/index.tsx#L65-L100

**Comment by tihuan** [comment]
Thanks so much for the issue, @seve ! PR out 🚀 

https://github.com/chanzuckerberg/sci-components/pull/122
