### ISSUE TITLE
Amend existing component: Notification

### ISSUE THREAD

**Issue by mdjmoore** [chanzuckerberg/sci-components#138]
## Component to amend

Notification

## Exists or New

Exists

## Visual

N/A

## Context

from slack: 
this is something small, but I think the dismissDirection prop is confusingly named, I think I would prefer for this prop to be named something like slideDirection since this is being used by the Slide animation for Notification onExit and onEnter? Additionally, when I dismiss the notification it just disappears, there is no associated animation.

**Comment by mmmmmmaya** [comment]
@chanzuckerberg/sds-design what do you think here?

**Comment by mmmmmmaya** [comment]
https://app.shortcut.com/sci-design-system/story/204673/updates-to-dismissdirection-prop-name-and-verify-slide-animation-working-properly
