### ISSUE TITLE
Link with Button styling

### ISSUE THREAD

**Issue by ehoops-zz** [chanzuckerberg/sci-components#31]
In order to maintain accessibility, I needed to use a link that was styled like a button.  I see that material UI handles the opposite case - a button that looks like a link - but I couldn't find this one.  I ended up styling an `<a>` tag.  If anyone else would use this, let me know and I can add it to the design system.

<img width="227" alt="Screen Shot 2021-06-24 at 6 33 34 PM" src="https://user-images.githubusercontent.com/8015489/123355552-bce62f00-d51a-11eb-8682-7ff62bec0e57.png">

**Comment by ehoops** [comment]
I also ended up making one that was the opposite.  This seems pretty common.  Including both of these in the design system will help make accessibility easier.

**Comment by ehoops-cz** [comment]
Closing this.  Buttons now have the component prop which solves this issue.
