### ISSUE TITLE
Link text-decoration underline

### ISSUE THREAD

**Issue by ehoops-zz** [chanzuckerberg/sci-components#32]
When I use the default Link component, it is missing `text-decoration: underline`.  I think this should be the default since it matches the default HTML.  

<img width="132" alt="Screen Shot 2021-06-29 at 4 31 06 PM" src="https://user-images.githubusercontent.com/8015489/123880416-79fbd100-d8f7-11eb-85c6-3faa0419bc7f.png">

**Comment by ehoops** [comment]
I'm also seeing this in the console, which might be related: 
<img width="498" alt="Screen Shot 2021-06-30 at 12 53 22 PM" src="https://user-images.githubusercontent.com/8015489/124023099-71140980-d9a2-11eb-8fe3-98d2fedf2767.png">

**Comment by mmmmmmaya** [comment]
Resolved https://zeroheight.com/009eaf17b/v/latest/p/78d741-text-links
