### ISSUE TITLE
New minimal single-select InputDropdown Design

### ISSUE THREAD

**Issue by cathystoli** [chanzuckerberg/sci-components#343]
### Description:
Creating the design for the new minimal single select input dropdown based off of the need of the ID team 

- [x] Alignment from the designers on the team
- [x] Update Figma component to reflect visual change
- [x] Update Zeroheight documentation including updated spacing rules

---

### Related Tickets

- #337 
- #402 
- #437 
- #438

**Comment by clarsen-czi** [comment]
Blocked for release until we implement #437
