### ISSUE TITLE
Amend existing component: Button

### ISSUE THREAD

**Issue by clarsen-czi** [chanzuckerberg/sci-components#363]
## Component to amend

`Button` – rounded and square variants

## Exists or New

The component currently exists, this will simply be restructuring it to accept a color prop 

## Acceptance criteria

- New `color` prop added to existing `Button` component (rounded and square variants, both with icon and without icon)
- `color: error` will result in text and background colors as follows:
    - `state: default` = `background-color: error400`
    - `state: hover` = `background-color: error500`
    - `state: pressed` = `background-color: error600`
    - Text color for default, hover, and pressed states = `white`
- Text and background colors for `disabled: true` (matches disabled colors used on primary variant)
    - `background-color: gray300`
    - `color: gray400`

## Visual

<img width="158" alt="Screenshot 2023-02-22 at 12 34 10" src="https://user-images.githubusercontent.com/87045841/220753768-1b1c1548-50bf-4687-83e4-4af1f011ea25.png">
<img width="158" alt="Screenshot 2023-02-22 at 12 34 15" src="https://user-images.githubusercontent.com/87045841/220753771-86e09888-8ab1-40de-b8af-af663284cb71.png">

## Context

This variant had already been designed, yet never added into the SDS codebase; it is now needed by the CZ ID team.

See this [Slack thread](https://czi-sci.slack.com/archives/C024AUM646Q/p1642799146033800) for additional context

**Comment by masoudmanson** [comment]
#761
