### ISSUE TITLE
Dropdown press delete in search bar deselect items

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/sci-components#376]
context: https://czi-sci.slack.com/archives/C032S43KKFV/p1678296205703739?thread_ts=1678296154.403999&cid=C032S43KKFV

repro:
Set multiple to true
Select some items in the Dropdown
Go to search bar and press “delete” key
Notice that selected items are now being deselected

https://user-images.githubusercontent.com/6309723/223857936-c846b3e9-4d8b-471d-8f93-546c34d31546.mov

**Comment by masoudmanson** [comment]
Resolved in this PR #386
