### ISSUE TITLE
Document: Jump-to Navigation

### ISSUE THREAD

**Issue by clarsen-czi** [chanzuckerberg/sci-components#380]
- [x] Document on SDS Zeroheight
    - https://sds.czi.design/009eaf17b/p/5552ba-navigation/b/065f46
- [x] Document on CZ ID Zeroheight
    - https://sds.czi.design/009eaf17b/p/041822-navigation/b/621251
- [x] Document on napari hub + .org Zeroheight
    - https://sds.czi.design/009eaf17b/p/106964-navigation/b/19c567

---

- Design ticket: #378 
- Implementation ticket: #426

**Comment by cathystoli** [comment]
@clarsen-czi can you add the link for the documentation?

**Comment by clarsen-czi** [comment]
@cathystoli added the links above
