### ISSUE TITLE
Document: Table

### ISSUE THREAD

**Issue by clarsen-czi** [chanzuckerberg/sci-components#382]
- [x] Document on SDS Zeroheight
    - https://sds.czi.design/009eaf17b/p/1647a1-tables/b/065f46
- [x] Document on CZ ID Zeroheight
    - https://sds.czi.design/009eaf17b/p/169c5e-tables/b/00d863
- [x] Document on napari hub + .org Zeroheight
    - https://sds.czi.design/009eaf17b/p/781d66-tables/b/40d3a9

---

- [x] Documentation reviewed

**Comment by clarsen-czi** [comment]
@karenliang0 will be reviewing the documentation in Zeroheight

**Comment by clarsen-czi** [comment]
@cathystoli added in links to the docs above.

**Comment by cathystoli** [comment]
Looks great! I am closing as I push out release notes
