### ISSUE TITLE
Update documentation for DropdownMenu

### ISSUE THREAD

**Issue by clarsen-czi** [chanzuckerberg/sci-components#387]
Update Zeroheight documentation for Dropdown Menu components. Current documentation reflects the previous structure of the component which has gone through a major overhaul.

- [x] Design and high level outline

### Steps
Updates to [new Code tab](https://czi.zeroheight.com/styleguide/s/66099/p/42bdf2-dropdown-menus/b/177008) (shown as hidden in Zeroheight editor) needed for all three components—DropdownMenu, MenuItem, Dropdown:
- [x] Differences between MUI and SDS
- [x] Link to MUI documentation
- [x] Update prop tables
- [x] Add code to interactive blocks
- [x] Add any additional code examples outside of Default
- [x] Incorporate nuances from the section below into the appropriate place
- [x] Build out extra code recipes for specific complex scenarios (see below)

---

### Specific nuances to document:
SDS table and other components - Each time a table column is shown/hidden a new table object is created.  This causes components within the table to remount.  This can be a problem with DropdownMenu if the menu is supposed to stay open while the columns are hidden/shown because the anchor element also gets recreated.  To resolve this, move the DropdownMenu anchor element outside of the table or use the pendingState and only show/hide the columns when closing the dropdown.

---

### Extra code recipes to add for specific complex scenarios:
- [x] `isOptionEqualToValue`
- [x] `noOptionsText` (add to existing search example)
- [x] `onInputChange`
- [x] `PopperBaseProps` (and add to Props table in documentation)
- [x] `PopperComponent`

**Comment by liaprins** [comment]
Here's a link to a doc where I started to collect my notes, questions, research, etc:
https://docs.google.com/document/d/1Inp2-taz6H52oEi0Y3bS23va6TLRJfDkZa3cWZD2FZM/edit#

**Comment by liaprins** [comment]
Link to Code tab with documentation and more basic code examples:
https://czi.zeroheight.com/styleguide/s/66099/p/42bdf2-dropdown-menus/b/177008/t/47bb46

Link to Component Recipes tab with more complex examples:
https://czi.zeroheight.com/styleguide/s/66099/p/42bdf2-dropdown-menus/b/263683

@masoudmanson and @tihuan if either (or both) of you could take a look at the code examples and documentation in the links above, that would be so so helpful, whenever you get a chance! I will hopefully be able to snag some time to make updates as needed during HQ week. Tahnks!
