### ISSUE TITLE
InputDropdown vs Dropdown documentation

### ISSUE THREAD

**Issue by cathystoli** [chanzuckerberg/sci-components#402]
~~Hey team! I have a question about the [dropdown component](https://chanzuckerberg.github.io/sci-components/?path=/story/dropdown--default). The current implementation doesn’t match the [Zeroheight documentation](https://zeroheight.com/009eaf17b/v/latest/p/543108-filters/b/065f46/t/197e55) or [Figma library](https://www.figma.com/file/OUhUAMQ3xsKIu7iY7J37G5/SDS-Components?node-id=332%3A2&t=kp6x50tFYCTsgKBl-1).
Expected
Closed: color: gray[500]
Hover: color: gray[600] and no background
Actual
Closed: color: gray[black]
Hover: background: gray[100] ?~~

Addition by Connor after chatting with the team:

It sounds like the main issue was there was confusion around what the text and chevron colors should be in the minimal dropdown input.

To fix it follow these specs:

Label text–
Default: gray500;
Hover: black;
Active: black;
Disabled: gray300;

Value (aka subtitle) text–
Default: gray500;
Hover: black;
Active: black;
Disabled: gray300;

Chevron–
Default: gray500;
Hover: black;
Active: primary400;
Disabled: gray300;

Container background (currently implemented accurately)–
Default: none;
Hover: gray100;
Active: gray100;
Disabled: none;

I've updated the specs in Figma to reflect this: https://www.figma.com/file/RAIg2Gzsw2QylzY28LYsl5/InputDropdown-Exploration?node-id=55%3A539&t=BbLweUBYc5pe5Df9-1

**Comment by cathystoli** [comment]
@clarsen-czi for this ticket can we also pull up why the initial change was made?

**Comment by clarsen-czi** [comment]
@cathystoli what do you mean "pull up" ? Do you mean add it into the ticket or add it into the documentation?

**Comment by cathystoli** [comment]
Oh sorry that was very jargony :trollface: I meant can we summarize in this ticket? Dana from the single cell team was asking

**Comment by clarsen-czi** [comment]
@cathystoli Ok after chatting through it on slack, I believe I came to the root of the issue which is the label text and chevron colors were not appearing as expected by the team. I've amended the original ticket above to provide direction.

lmk if that makes sense!
