### ISSUE TITLE
Clicking outside of a dropdown - Update to expected behavior

### ISSUE THREAD

**Issue by cathystoli** [chanzuckerberg/sci-components#403]
Problem: When you click out of a `DropdownMenu` component it applies changes
 
Slack convo: https://czi-sci.slack.com/archives/C032S43KKFV/p1679696875607709 

Figma & expected behavior: https://www.figma.com/file/35JMdsMEL252zYWthRG1ui/Dropdown-Variation---Apply-button?node-id=15%3A66531&t=N78JbQ8OlEtY4x4O-1

**Comment by cathystoli** [comment]
We left some comments in the figma based off a convo in sprint planning

**Comment by clarsen-czi** [comment]
As far as I understood it, the DropdownMenu variant that includes buttons is a CZ ID snowflake. Because of this, whatever functionality the team wants to assign when users click outside of the menu is up to them, but shouldn't affect how the SDS component works.

**Comment by clarsen-czi** [comment]
Just chatted with Jenn and she helped remind me that we do have the variant with buttons as part of the SDS codebase, we just don't have it documented in Zeroheight and the "click away" behavior needs to be updated.

What needs to be done:

- Documentation needs to be updated to include variant with Buttons as an SDS component (not just CZ ID)
    - Including explanation of what's supposed to happen when the user clicks outside of the dropdown (specs outlined in the Figma file above)
