### ISSUE TITLE
Update slider documentation

### ISSUE THREAD

**Issue by cathystoli** [chanzuckerberg/sci-components#405]
Component Name: Slider - does `tickMarks` prop exist?
Issue Description: Hey there. The docs indicate that there's an optional `tickMarks` prop on the `InputSlider` component, but I'm not seeing it in the codebase. Am I overlooking something silly here? I'd expect to see it [here](https://github.com/chanzuckerberg/sci-components/blob/main/src/core/InputSlider/style.ts#L10)
It looks like this is actually an MUI prop, `marks`. Suggest just updating the SDS docs to remove this prop, as this is available in the base component and doesn't seem to be altered by the SDS implementation. (edited)

**Comment by clarsen-czi** [comment]
Updated the docs to change `tickMarks` to `marks`
