### ISSUE TITLE
Amend dropdownMenu to stay open only for the button variant

### ISSUE THREAD

**Issue by masoudmanson** [chanzuckerberg/sci-components#414]
## DropdownMenu

Figma design: https://www.figma.com/file/35JMdsMEL252zYWthRG1ui/Dropdown-Variation---Apply-button?node-id=15-66417&t=470d4wIePuOD02HE-0

**Comment by cathystoli** [comment]
https://github.com/chanzuckerberg/sci-components/issues/419 --> blocking this release
