### ISSUE TITLE
Investigate Stackblitz

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/sci-components#415]
1. Does Stackbliz fulfill our needs?
1. Can we use Stackblitz without connecting to any Github repo (therefore no write access)
1. Can we test if Stackblitz is stable that it doesn’t randomly lose code like Codesandbox :meow-sad-life:
1. If the questions above all work out, we can then ask security team to review Stackblitz and go from there!

**Comment by masoudmanson** [comment]
Using ZeroHeight's new Live code feature, we don't need to use CodeSandbox or Stackblitz for component demos.
