### ISSUE TITLE
Implement: Jump-to Navigation

### ISSUE THREAD

**Issue by clarsen-czi** [chanzuckerberg/sci-components#426]
Spec sheet for implementation [here](https://www.figma.com/file/EaRifXLFs54XTjO1Mlszkg/Science-Design-System-Reference?node-id=10902%3A107306&t=5FJpsR1HkbDz5y1U-1).

---

- Design ticket: #378 
- Documentation ticket: #380

**Comment by clarsen-czi** [comment]
@cathystoli I marked this as a P1 because Single Cell will be needing this component soon, so I think ideally let's work on it next sprint?

**Comment by cathystoli** [comment]
@clarsen-czi that sounds right, just added to up next

**Comment by masoudmanson** [comment]
@cathystoli Just got started on this ticket.
