### ISSUE TITLE
Implement: InputDropdown

### ISSUE THREAD

**Issue by clarsen-czi** [chanzuckerberg/sci-components#437]
### Background

The current `InputDropdown` component has been redesigned and now features two distinct types: `label` and `value` with accompanying visual changes. This ticket is to update our current component to align with this new design.

 ---

### Spec sheet

Found [here](https://www.figma.com/file/EaRifXLFs54XTjO1Mlszkg/Science-Design-System-Reference?node-id=10963%3A107422&t=u65Hp4Wci4VQarVB-1).

### Out of Scope 

- Multiselect value dropdown (expanded to use cases that are more edge cases related to multiselect for dropdowns that we do not have use cases for and woudl require extra designs)

---

### Related tickets

- Design ticket: #349

**Comment by clarsen-czi** [comment]
@tihuan based on our pointing discussing yesterday, sounds like @masoudmanson will actually be taking this on

**Comment by tihuan** [comment]
Oh perfect thank you! I'm actually on call next week for SC, so probably won't have much coding capacity. But the week after that I should be able to work on something!
