### ISSUE TITLE
Update Code documentation for InputDropdown

### ISSUE THREAD

**Issue by clarsen-czi** [chanzuckerberg/sci-components#471]
Updates to new Code tab (shown as hidden in Zeroheight editor) documentation in Zeroheight for InputDropdown component. Current documentation reflects the previous structure of the component which has gone through a major overhaul.

Need to update the component in the codebase first before updating documentation: #437 

### Steps
Update Code documentation in [new Code tab](https://czi.zeroheight.com/styleguide/s/66099/p/1004b1-dropdown-input/b/775bfc) (shown as hidden in Zeroheight editor):
- [x] Differences between MUI and SDS
- [x] Link to MUI documentation
- [x] Update prop tables
- [x] Add code to interactive block
- [x] Add any additional code examples outside of Default

**Comment by masoudmanson** [comment]
Link to Code tab with documentation and more basic code examples:
[https://czi.zeroheight.com/styleguide/s/66099/p/1004b1-dropdown-input/b/775bfc](https://czi.zeroheight.com/styleguide/s/66099/p/1004b1-dropdown-input/b/775bfc)
