### ISSUE TITLE
Focus state appearing on Icon Buttons when clicked on

### ISSUE THREAD

**Issue by clarsen-czi** [chanzuckerberg/sci-components#482]
### Background

When Icon Buttons are clicked on their focus state is triggered. This state should only appear when they are navigated to using keyboards, not clicked on with mice. This has been noticed in both CellxGene and CZ ID (see examples below)

---

### Examples

**CZ ID:**

![Image](https://github.com/chanzuckerberg/sci-components/assets/87045841/008628f7-1bc5-493e-9a00-abf5381b2434)

**CellxGene:**

![Image](https://github.com/chanzuckerberg/sci-components/assets/87045841/17fbca54-97db-475c-853c-6ca99478ce24)

**Comment by masoudmanson** [comment]
Hey @cathystoli, this issue has already been resolved. Just tagging @clarsen-czi to double-check the styles for confirmation.

**Comment by clarsen-czi** [comment]
@masoudmanson Thanks for the link! Everything looks great to me, so I say let's close this one out.
