### ISSUE TITLE
Autocomplete component

### ISSUE THREAD

**Issue by cathystoli** [chanzuckerberg/sci-components#489]
**What**: Build out the autocomplete component to enable type ahead search outside of in input dropdown 

**Use cases**: The primary use case in Single cell is to use this in the multi-panel dropdown but we want to enable partner teams to also use this component on its own.  
- [ ] P0: Multiselect following the pattern of Dropdown menu
- [x] P2: Single Select, no text getting replaced in the text box 

**Items to discuss for later:** 
- [ ] P2: For multi-select, show the multi select chips inside text box lie the MUI example as a prop 
- [ ] Action varient - P0 for multicolumn
- [ ] Search icon on the left
- [ ] remove input to the search bar
- [ ] Floating label in the search bar (across all components)

**MUI component**: https://mui.com/material-ui/react-autocomplete/

**Requesting team**: Single Cell 

**Timing**: By 8/18

**Customizations**: None requested 

**Figma**: https://www.figma.com/file/lLYGh38Xuun8iyYR19SbjH/Advanced-Dropdowns?type=design&node-id=7%3A554&mode=design&t=APVdGDklfnOmvNji-1

**Comment by cathystoli** [comment]
@hthomas-czi Can you add any other details or timing?

**Comment by tihuan** [comment]
@cathystoli @masoudmanson  Feature quest 😆 🙏 

Single Cell Team is wondering if we could add optional "Cancel"/"Apply" buttons to the component as well like we have on SDS Dropdown. But if expands the scope too much, SC can implement it too!



![Image](https://github.com/chanzuckerberg/sci-components/assets/6309723/4a1e9942-c460-41e3-9eb0-ccf6b862c100)


Thank you!

CC: @hthomas-czi
