### ISSUE TITLE
InputSearch not rendering `intent` correctly in Storybook

### ISSUE THREAD

**Issue by liaprins** [chanzuckerberg/sci-components#496]
**Describe the bug**
InputSearch component maintains the visual `default` state and coloring even when its `intent` is changed to `error` or `warning` (instead of `default`). This is happening in Storybook, but I am not sure if it is happening for the component in products, [so have reached out in the sds-collab Slack channel to ask others if they see this happening](https://czi-sci.slack.com/archives/C024AUM646Q/p1685748197847239).

**To Reproduce**
1. Go to InputSearch's Default or Live Preview story pages in Storybook
2. In the control panel, change the "intent" setting to "warning" or "error"

**Expected behavior**
The outline of the searchbox should change to orange or red, but it maintains the gray outline for the "default" option.

**Comment by cathystoli** [comment]
@liaprins can you verify this?

**Comment by liaprins** [comment]
Yes, this is fixed! 🥳
