### ISSUE TITLE
Update napari hub + .org Tag component

### ISSUE THREAD

**Issue by clarsen-czi** [chanzuckerberg/sci-components#505]
### Background
`Tag` component in the napari hub + .org library needs to be updated to the latest design specs. This includes:

- Splitting the component into two separate components (aligning with master SDS library structure): `Tag` and `TagFilter`
- Update color across states to align with design specs

### Design file

https://www.figma.com/file/MviVcecNZYJ6XB8QwpZAPu/Hub-Home-page-Reorg?type=design&node-id=851%3A28506&t=XNLfkwYLwYEFo0cp-1

### Related tickets

- [ ] #508

**Comment by cathystoli** [comment]
@Janeece Can you review this please for release?

**Comment by Janeece** [comment]
@clarsen-czi @cathystoli LGTM!

**Comment by clarsen-czi** [comment]
Thanks Janeece! We'll push this out at our next release, next Wednesday.
