### ISSUE TITLE
Update text styles in napari hub + .org library

### ISSUE THREAD

**Issue by clarsen-czi** [chanzuckerberg/sci-components#506]
### Background
Janeece has done an audit of type sizes and has recommended updating font sizes for the following types styles:
- Site Title – narrow
- H1 – narrow
- H2 – narrow
- H3 – narrow
- H4 – narrow
- H5 – narrow
- H6 – narrow and wide
- bodyXs

### Design file

https://www.figma.com/file/UuSPthD5LmDWhCCXRr2O2d/Hub-SEO---Typography-Size?type=design&node-id=8%3A942&t=rwSDNq0R8tpKABmg-1

### Related tickets
- [ ] #507

**Comment by cathystoli** [comment]
@Janeece Can you review this please for release?

**Comment by Janeece** [comment]
@clarsen-czi @cathystoli LGTM, thank you!

**Comment by clarsen-czi** [comment]
Amazing! Thanks for taking a look, Janeece. We'll push these out at our next release, next Wednesday.
