### ISSUE TITLE
Implement: VirusCircleS icon

### ISSUE THREAD

**Issue by clarsen-czi** [chanzuckerberg/sci-components#509]
### Success criteria
Add `VirusCircleS` icon into codebase

Sizes needed:
- large
- extraLarge

### Icon SVG
https://drive.google.com/open?id=1QD4NcIzhtf-TUO28AEzSkrrloQXpv_F6&usp=drive_fs

### Related tickets
- [x] #425

**Comment by cathystoli** [comment]
@liaprins tagging you here to review - Wondering if this would make sense for you to pick up when you have capacity if you want a break from documentation land

**Comment by liaprins** [comment]
Yeah this sounds good, I will look into it soon!
