### ISSUE TITLE
Navigation Documentation Updates

### ISSUE THREAD

**Issue by cathystoli** [chanzuckerberg/sci-components#516]
- [ ] Identify examples to create interactive code samples for
- [ ] Create interactive code samples for identified scenarios
- [ ] Differences between MUI and SDS
- [ ] Link to MUI documentation
- [ ] Update prop tables
- [ ] Add code to interactive blocks
- [ ] Add any additional code examples outside of Default
- [ ] Incorporate nuances from the section below into the appropriate place

**Comment by liaprins** [comment]
Now documentation updates are covered by an overarching single GH issue #539
