### ISSUE TITLE
`details` doesn't appear when used on a custom component menu item within DropdownMenu

### ISSUE THREAD

**Issue by liaprins** [chanzuckerberg/sci-components#522]
**Describe the bug**
`details` doesn't appear when used on a custom component menu item within DropdownMenu

**To Reproduce**
1. Go to the DropdownMenu Zeroheight documentation
2. Scroll down to the "DropdownMenu with components in place of menu items" interactive code example
3. Within the MENU_ITEMS const array, add the following `details` property to the last object in the array:
`details: "Details test!",`

**Expected behavior**
"Details test!" should display in small light grey text below the last menu item (a grey Tag component) in the example, but nothing shows up.

**Screenshots**
_See the last row_
![Screenshot 2023-06-14 at 2 38 06 PM](https://github.com/chanzuckerberg/sci-components/assets/17435353/5b358ee7-b82f-4e1e-9ed1-31fd6e98235e)

**Additional context**
Instead of doing this in teh Zeroheight code examples, you can test it in the code for the Default (or other DropdownMenu-related) story in Storybook. I also tested this there, and details still does not appear when used in conjunction with any component used in place of a menu item. However, `count` and `sdsIcon` _do_ render properly.

- [ ] When this bug is fixed, please update the relevant part of the DropdownMenu's Zeroheight documentation (the section called "DropdownMenu with components in place of menu items") by adding `details: "Details",` to the last object in the MENU_ITEMS array, and updating the last couple bullet points of the corresponding documentation so that `details` is included as optional metadata and not mentioned as a bug. Thanks! ❣️

**Comment by cathystoli** [comment]
Not a bug, as designed
