### ISSUE TITLE
Implement: ChevronLeft2Small and ChevronRight2Small

### ISSUE THREAD

**Issue by cathystoli** [chanzuckerberg/sci-components#530]
**Component Name:** ChevronLeft2Small and ChevronRight2Small

**Component Requirements:** Hi all, I ran these 2 new icons by the team at a previous SDS team meeting! The team agreed we should add it.

**Icons can be found on the Google Drive:**
- [x] [ChevronLeft2Small](https://drive.google.com/file/d/12KA19l3nMpaf7bGvyb2qrIv8joq4o_O7/view?usp=drive_link)
- [x] [ChevronRight2Small](https://drive.google.com/file/d/12KWlMVeDfxwhsu6DQa30cgrtbcmL7_ae/view?usp=drive_link)

**Team(s) Requesting:** CZ ID

---

**Related tickets:**

- [ ] #531
- [ ] #532

**Comment by liaprins** [comment]
Closed via #547
