### ISSUE TITLE
Add "code" icon to the SDS icons library

### ISSUE THREAD

**Issue by cathystoli** [chanzuckerberg/sci-components#567]
Icon design in Figma here: https://www.figma.com/file/pDKU0CdSzpSWGaoXXQVJLz/v0-hub-final-designs?node-id=2602%3A122&t=3GuhKGo69fP2FOzK-1 
- [x] Add icon into SDS Icons library in Figma

**Comment by masoudmanson** [comment]
Please refer to this guide for instructions on adding new icons to SDS: 

https://github.com/chanzuckerberg/sci-components/blob/main/packages/components/docs/how-to-add-icon.md
