### ISSUE TITLE
Update ButtonIcon component so that it uses instance swap for the icon so the color of the icon is correct

### ISSUE THREAD

**Issue by cathystoli** [chanzuckerberg/sci-components#570]

**Comment by clarsen-czi** [comment]
No longer needed as `ButtonIcon` variants have been absorbed into other components (tickets here: #743 , #744 )

**Comment by clarsen-czi** [comment]
No longer needed as ButtonIcon variants have been absorbed into other components (tickets here: https://github.com/chanzuckerberg/sci-components/issues/743 , https://github.com/chanzuckerberg/sci-components/issues/744 )
