### ISSUE TITLE
Add disabled state to Tag component

### ISSUE THREAD

**Issue by cathystoli** [chanzuckerberg/sci-components#571]
Text color gray300
Background color gray200

**Comment by clarsen-czi** [comment]
@cathystoli do you remember if this was to allow individual Tabs to be displayed as disabled? We currently have the ability to disable an entire Tab group but not individual Tabs (which is what makes me assume that's what's being asked for)

**Comment by clarsen-czi** [comment]
@cathystoli confirmed there is no record of this request so closing for now
