### ISSUE TITLE
Alerts: different icons?

### ISSUE THREAD

**Issue by flekkowich** [chanzuckerberg/sci-components#61]
**Describe the bug**
For [Alerts](https://chanzuckerberg.github.io/sci-components/?path=/story/alert--elevated) do we want to consider different icons? 

**To Reproduce**
Go to [Alerts](https://chanzuckerberg.github.io/sci-components/?path=/story/alert--elevated)

**Expected behavior**
Different icons for each alert level

**Comment by masoudmanson** [comment]
The `Alert` component has been flagged to be deprecated. We can close this issue.
