### ISSUE TITLE
Remove `orientation` prop from InputSlider

### ISSUE THREAD

**Issue by clarsen-czi** [chanzuckerberg/sci-components#621]
There shouldn't be an `orientation` prop on InputSlider; the only available orientation should be horizontal.

**Comment by masoudmanson** [comment]
## How to fix

The MUI [slider](https://mui.com/material-ui/react-slider/) offers both `horizontal` and `vertical` orientations within the Slider component. To limit the orientation exclusively to `horizontal`, we'll need to set the orientation at the component level by hardcoding it. 

Simply go to [this line](https://github.com/chanzuckerberg/sci-components/blob/0314183c8a60044bdc1579d3dc27209094d5188d/packages/components/src/core/InputSlider/index.tsx#L11) and add orientation="horizontal" after spreading the props.

```javascript
const InputSlider = forwardRef<HTMLSpanElement, InputSliderExtraProps>(
  (props, ref) => {
    return <StyledSlider ref={ref} {...props} orientation="horizontal" />;
  }
);
```

Additionally, we'll remove any redundant styles associated with the vertical orientation to ensure alignment with the desired horizontal orientation.

1. Remove Vertical styles definition [here](https://github.com/chanzuckerberg/sci-components/blob/0314183c8a60044bdc1579d3dc27209094d5188d/packages/components/src/core/InputSlider/style.ts#L129)
2. Remove redundant condition [here](https://github.com/chanzuckerberg/sci-components/blob/0314183c8a60044bdc1579d3dc27209094d5188d/packages/components/src/core/InputSlider/style.ts#L195)

**Comment by masoudmanson** [comment]
@tihuan, I'm reconsidering the approach of enforcing the orientation as [previously described](https://github.com/chanzuckerberg/sci-components/issues/621#issuecomment-1828433027). What are your thoughts on whether this method is the appropriate way to achieve the desired result? 🤔

**Comment by tihuan** [comment]
Thanks for the detailed notes, @masoudmanson !

For enforcing horizontal, it feels like your approach above makes sense to me, but maybe I'm missing some concerns you have in mind!
