### ISSUE TITLE
Figma Refactor: Button

### ISSUE THREAD

**Issue by clarsen-czi** [chanzuckerberg/sci-components#640]
### Design

**Features to Implement**
- [x] Min width
- [x] Min height
- [x] Boolean
- [x] Text
- [x] Variables
- [x] Instance swap
- [x] Interactive components

**Related Tickets**
- [x] #671 
- [x] https://github.com/chanzuckerberg/sci-components/issues/743

---

### Design QA

---

### Engineering

**Updates to make**

- [x] Top/bottom padding: `spaceXxs` (4px), resulting in height: 32px on rounded and square; 24px on minimal
- [x] Min-width: 120px on rounded and square; hug on minimal
- [x] Left/right padding: `spaceM` (12px) on rounded and square; 0px on minimal
- [x] When displaying with an icon, padding between icon and label: `spaceS` (8px) on rounded and square; `spaceXxs` (4px) on minimal
- [x] Add ability to include an icon to minimal button secondary variant
- [x] Add `sdsStyle: icon` to `Button` component; follow new design guidelines found [here](https://www.figma.com/file/CuKxdbQsexhca5hnB4Z9LN/SDS-Figma-Refactor?type=design&node-id=1357%3A4803&mode=design&t=S1ZIqbGzQWxRKOnK-1)

**NOTE:** any components currently using a nested `IconButton` component will need to have it replaced by the new `Button` or `ButtonDropdown` icon variant depending on functionality. @masoudmanson you and I can work together to identify these

Design review

- [x] Remove the `min-width`
- [x] left and right padding should be `spaceM` (12px)
- [x] There should be a `negative` variant available that uses the negative fill, hover, and pressed color variables respectively
- [x] Padding between Label and icon on Rounded and Square buttons should be `spaceS` (8px)
- [x] Padding between Label and icon on Minimal button should be `spaceXxs` (4px)
- [x] On the minimal variant with icon, the version of the download icon should be the size: s version (without the cloud) 
- [x] On the minimal variant, both primary and secondary should be available with an icon (previously only primary was available with an icon)
- [x] On the minimal variant there seems to be a min-width applied, but there should not be (there is also no left/right padding; the width should be hug and thus dictated by width of the content inside)
- [x] On primary and secondary variants of the icon variant:
On size: M, the background that appears on hover and active should be 38px x 38px (currently 36px x 36px)
On size: S, the background that appears on hover and active should be 30px x 30px (currently 28px x 28px)
- [x] On the primary variant of the icon variant I would recommend using a different icon for demonstration since the Cube icon you're using only comes in size: XL and L, which are too large to be used in the small variant of that button (maybe use the Copy icon since it comes in all sizes, but feel free to use any icon that comes in all sizes)
- [x] I've noticed that you're using state: active for when the button is pressed. I don't believe there should be an active state since this button doesn't act as a toggle, so it can't be "active" or "inactive" it can only be pressed or not. In Figma I'm using state: pressed; would that make sense here as well or is there something I'm not understanding for how you have to implement it in code where state: pressed won't work?

**Comment by masoudmanson** [comment]
@clarsen-czi 

- [ ] Top/bottom padding: `spaceXxs` (4px), resulting in height: 32px on rounded and square; 24px on minimal

There seems to be an inconsistency with the height calculation for the Button component. Currently, the Button has `fontBodyXs` with a line-height of 20px. When adding a `spaceXxs` padding on top and bottom, the resulting height is 28px for the rounded and square buttons, instead of the expected 32px. The height is correctly 24px on the minimal variant.

**Comment by clarsen-czi** [comment]
@masoudmanson 

Ahh I see what's going on. Looks like when there's an Icon included on the `Button` then the `spaceXxs` will work (since the hight of the Icon `size: l` used in the `Button` is 24px, plus 4px top and bottom padding = 32px); when it's just text on the `Button`, then the padding needs to be `spaceXs`(6px): 20px for the height of the text + 6px top and bottom padding = 32px.

Hopefully that makes sense and will work to fix the issue!

**Comment by masoudmanson** [comment]
@clarsen-czi 

Ahh that makes sense now, thanks for the explanation 🙏🏻
