### ISSUE TITLE
Add medium size Primary and Secondary IconButtons to SDS

### ISSUE THREAD

**Issue by cathystoli** [chanzuckerberg/sci-components#681]
Background:As we developed the Tertiary IconButton for SDS, we uncovered a need for a medium size Icon Button for Primary and Secondary types. This ticket will likely need to be broken up into design and eng tickets. 

Acceptance Criteria:

medium size height and width = 22px (icon size =`iconSizeL`)

medium size (`sdsSize: Medium`) is added to SDS Docs, including any defined usage/restrictions

medium size variant is added to Figma component

medium size variant is added to Code Repo (design should indicated if any warnings about size usage are needed)

Eng Notes:From Meagan:right now IconButton handles styling by prop type, so `sdsSize` and `sdsType` are handled independently. So adding another size is totally fine, we would just have another group of styles for the medium size. If you wanted to warn against using the medium size with another other style, we can follow what button is doing ([here](https://github.com/chanzuckerberg/sci-components/blob/main/src/core/Button/index.tsx#L26) ) and give a warning if someone tries to implement it

**Comment by clarsen-czi** [comment]
These features have been included in the new Icon variants of other components (tickets here: https://github.com/chanzuckerberg/sci-components/issues/743 , https://github.com/chanzuckerberg/sci-components/issues/744 ); `ButtonIcon` component has been removed from SDS library
