### ISSUE TITLE
ChevronLeft2 and ChevronRight2

### ISSUE THREAD

**Issue by cathystoli** [chanzuckerberg/sci-components#685]
Component Requirements: Hi all, I have a need for up and down direction double carets, can we add them to the sds components? Thanks!
Team(s) Requesting: CZ ID
Component Needed By: No urgent time frame! Sooner rather than later so it doesn't fall off our radar!
Requestor: Kevin Wang

---

Icon SVGs are saved here:

`ChevronDown2` – small: https://drive.google.com/file/d/12LW7CVgwkFOWujIPQeFdHgIccWNn95Kj/view?usp=drive_link
`ChevronUp2` – small: https://drive.google.com/file/d/12OfyuF87mYBm4_q2L7ut5ArRd6lxao6U/view?usp=drive_link

**Comment by cathystoli** [comment]
@clarsen-czi can you confirm that design work is needed?

**Comment by clarsen-czi** [comment]
@cathystoli yes very minimal design work will be needed since we'll just be leveraging the existing left and right carets

**Comment by clarsen-czi** [comment]
@cathystoli I've got them exported and added links to the ticket to where the SVGs are saved on the shared drive
