### ISSUE TITLE
Icon: Envelop

### ISSUE THREAD

**Issue by clarsen-czi** [chanzuckerberg/sci-components#689]
Add Envelop icon into SDS Icons codebase

Requester: Janeece

---

Icon SVG is saved here:

Envelope – small: https://drive.google.com/file/d/12Pa-KGXV6KEOB9_46bcYF-LpNO_eDa3c/view?usp=drive_link

**Comment by clarsen-czi** [comment]
@cathystoli while we're adding the other icons from #685 , let's add this one too.

**Comment by masoudmanson** [comment]
#740
