### ISSUE TITLE
Implement: Updated hover and pressed states for `Button` – minimal

### ISSUE THREAD

**Issue by clarsen-czi** [chanzuckerberg/sci-components#803]
Specs found [here](https://www.figma.com/design/hQ1kUAFzQvsXcq3ZtWiZAq/SDS-Complete?node-id=21-427&t=00ifZ20RbR7WvrgV-1).

**Comment by clarsen-czi** [comment]
@clarsen-czi update with link to specs in Figma

**Comment by masoudmanson** [comment]
Released with https://github.com/chanzuckerberg/sci-components/pull/815
