### ISSUE TITLE
Document: Update `Panel` docs

### ISSUE THREAD

**Issue by clarsen-czi** [chanzuckerberg/sci-components#812]
- [x] Update Guidelines documentation
- [x] Update Code documentation 
- [x] Add Code Examples and Component Recipes

**Comment by clarsen-czi** [comment]
Hey @masoudmanson I'm splitting this ticket into two parts, one for updating the Guidelines section of the `Panel` docs and the other for updating the Code section of the `Panel` docs. I've taken care of the Guidelines if you could please tackle the Code. Thank you!!

**Comment by masoudmanson** [comment]
Code Documentation Update:

The SDS vs MUI comparison and prop tables have been added to ZeroHeight. You can view them [here](https://czi.zeroheight.com/styleguide/s/66099/p/16422a-panels/b/14d41a).

Next, we need to publish the package to make it available for writing the code examples. This will be done after the PR is reviewed and the new version is published.
