### ISSUE TITLE
Implement: Narrow screen fonts

### ISSUE THREAD

**Issue by clarsen-czi** [chanzuckerberg/sci-components#842]
Implementation specs can be found here: https://www.figma.com/design/hQ1kUAFzQvsXcq3ZtWiZAq/SDS-v2-Complete?node-id=360-793&t=LxjLU9qOxReZzyg2-1

**Comment by masoudmanson** [comment]
Jeremy created a PR to add new narrow styles.

https://github.com/chanzuckerberg/sci-components/pull/884

**Comment by masoudmanson** [comment]
We also need to include these new narrow font styles in the design tokens to export them as CSS, SCSS, and Tailwind variables. I’ve created a new PR to add these variables on top of Jeremy’s PR.
