### ISSUE TITLE
Tooltips do not work on disabled buttons

### ISSUE THREAD

**Issue by rainandbare** [chanzuckerberg/sci-components#870]
**Describe the bug**
When using the Tooltip component around a disabled Button component - the hover action must not bubble up to the tooltip because the tooltip does not show up on hover.

**To Reproduce**
1. Create a Button Component and wrap it in a Tooltip
2. See tooltip appear!
3. Give the Button a `disabled={true}`
4. Hover on the disabled button 
5. See no tooltip appear

**Expected behavior**
Tooltip should be available on hover even on disabled buttons

**Screenshots**
![Screenshot 2024-10-09 at 11 53 40 AM](https://github.com/user-attachments/assets/7575f421-9cdd-4af6-bb90-db0dc555624f)

![Screenshot 2024-10-09 at 12 04 26 PM](https://github.com/user-attachments/assets/7731cd55-e287-4424-83a2-bfb02b14e76c)

![Screenshot 2024-10-09 at 12 04 18 PM](https://github.com/user-attachments/assets/3c0deb18-8771-4b6d-8e5f-67ecf3dfcffd)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome

**Additional context**
Happy to help with this but would love to hear any insight y'all have!

**Comment by rainandbare** [comment]
found it!
https://github.com/chanzuckerberg/sci-components/blob/d59af72ced81f4e4577aa85b6cd272a343170931/packages/components/src/core/Tooltip/index.tsx#L27C1-L30C4

Maybe we can add this to the Tooltip Docs here https://sds.czi.design/009eaf17b/p/74af45-tooltips/b/3989d2/t/page-74af45-76022694-3989d2-21?

**Comment by rainandbare** [comment]
And it is right here in my code editor - oh my goodness - you have already done such a good job trying to help me solve this easily. 
![Screenshot 2024-10-09 at 12 37 18 PM](https://github.com/user-attachments/assets/ad2051b2-865d-4404-a8a0-239c6b46b335)

**Comment by masoudmanson** [comment]
We've also added a code example to demonstrate this on ZeroHeight. Thanks for the suggestion! 🥳🎉😬

https://sds.czi.design/009eaf17b/p/74af45-tooltips/t/3543fca49d
