### ISSUE TITLE
Link component underline only applies on last line

### ISSUE THREAD

**Issue by crispipear** [chanzuckerberg/sci-components#879]
**Describe the bug**
Link component underline only applies on last line

**To Reproduce**
1. Create a Link component
2. Use longer string for the text wrapped by Link

**Expected behavior**
The underline should appear on every line

**Screenshots**
<img width="455" alt="image" src="https://github.com/user-attachments/assets/4bde0db9-0684-4e9b-819e-c21f066d8cdc">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS Ventura 13.3.1
 - Browser [e.g. chrome, safari] firefox 125.0.3

**Comment by masoudmanson** [comment]
Hi @crispipear,
Thanks for reporting the bug. I’ve created a fix for the `Link` component, and it will be published once we get approval from the design team. 

Here is the PR: #880

**Comment by masoudmanson** [comment]
### 10/23 Release

:computer: Coded Library (@czi-sds/components@21.6.1)

#### :gift: New Features:
- Added makeSdsSemanticAppTheme style util

#### :bug: Bug Fixes:
- Fixed an issue where the underline for the Link component was applied only to the last line of text.
